### ISSUE TITLE
GCP Compute Engine Setup

### ISSUE THREAD

**Issue by manasouza** [manasouza/sfin-bills#40]
Service account setup:
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#applications

**Comment by manasouza** [comment]
Install Docker at VM instance:
https://docs.docker.com/install/linux/docker-ce/debian/

**Comment by manasouza** [comment]
Sequence:
Configure a **startup script** to get credentials
* Get credentials from Storage bucket
* Create dir `/root/.credentials/`
* Move JSON file to new dir

REF: https://cloud.google.com/compute/docs/startupscript

**Comment by manasouza** [comment]
Upload `Dockerfile` and push it to Container Registry

* Add `docker pull` to the **startup script**
* Add `docker run` with restart policy (https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy)

**Comment by manasouza** [comment]
Executed through Cloud Build and now got:
```
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /app/sfin_bills_server.js:58:39
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
```
May be something related to the created token. Next steps before testing again:
* Verify if the current code at image is updated
* Remove previous token information, if applicable

**Comment by manasouza** [comment]
UPDATE:
`prod` GCE instance setup done until sfinbills docker image installation:
* Need to execute first step on app (authentication)

**Comment by manasouza** [comment]
Authentication flow executed

Still stuck on the log:
```[INFO] current_month: novembro/2018```

Need to investigate (maybe adding some debug logs directly on docker image files)
