### ISSUE TITLE
Error on application setup

### ISSUE THREAD

**Issue by manasouza** [manasouza/sfin-bills#46]
```
[INFO] Authorize this app by visiting this url:  https://accounts.google.com/o/oauth2/auth?...
Enter the code from that page here: ...
[INFO] token stored to ...
.../sfin-bills/sfin_bills_server.js:91
      callback(oauth2Client, google);
      ^

TypeError: callback is not a function
    at .../sfin-bills/sfin_bills_server.js:91:7
    at .../sfin-bills/node_modules/google-auth-library/lib/auth/oauth2client.js:154:5
    at Request._callback (.../sfin-bills/node_modules/google-auth-library/lib/transporters.js:106:7)
    at Request.self.callback (.../sfin-bills/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (.../sfin-bills/node_modules/request/request.js:1126:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (.../sfin-bills/node_modules/request/request.js:1046:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by manasouza** [comment]
Validate with:
https://developers.google.com/sheets/api/quickstart/nodejs#step_3_set_up_the_sample

**Comment by manasouza** [comment]
When upgrading to googleapis 27.0.0, got an incompatibility with drive API v2
```
[ERROR] Error while trying to retrieve access token TypeError: google.drive is not a function
    at listSpecificModified (/home/manasses/git/sfin-bills/file_loader.js:22:28)
    at oAuth2Client.getToken (/home/manasses/git/sfin-bills/sfin_bills_server.js:76:7)
    at /home/manasses/git/sfin-bills/node_modules/googleapis/node_modules/google-auth-library/build/src/auth/oauth2client.js:157:45
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Reverted it to 24.0.0 (http://quabr.com/49001689/nodejs-command-line-application-that-makes-requests-to-the-drive-api)

**Comment by manasouza** [comment]
Obs:
```
googleapis 27.0.0 => google-auth-library 1.3.1

googleapis 24.0.0 => google-auth-library 0.12.0
```
the bump up of current google-auth-library in `package.json` to 0.12.0 did not work, so it's defined as 0.10.0
