### ISSUE TITLE
Update config mapping to Cloud Firestore

### ISSUE THREAD

**Issue by manasouza** [manasouza/sfin-bills#91]

**Comment by manasouza** [comment]
```
(node:521) UnhandledPromiseRejectionWarning: Error: Value for argument "field" is not a valid field path. Paths can't be empty and must not contain
    "*~/[]".
    at Object.validateFieldPath (/mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/node_modules/@google-cloud/firestore/build/src/path.js:564:15)
    at QueryDocumentSnapshot.get (/mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/node_modules/@google-cloud/firestore/build/src/document.js:343:16)
    at /mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/file_loader.js:99:44
    at /mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/node_modules/collections/generic-collection.js:53:18
    at Dict.reduce (/mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/node_modules/collections/_dict.js:178:26)
    at Dict.GenericCollection.forEach (/mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/node_modules/collections/generic-collection.js:52:17)
    at Object.processFiles (/mnt/c/Users/Manasses_de_Souza/Development/git/sfin-bills/file_loader.js:97:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:521) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by manasouza** [comment]
Fixed
