### ISSUE TITLE
Fail to process elements that will update the same cell in same operation

### ISSUE THREAD

**Issue by manasouza** [manasouza/sfin-bills#94]
https://console.cloud.google.com/logs/query;timeRange=2021-07-04T20:22:10.138Z%2F2021-07-04T22:22:10.138Z;cursorTimestamp=2021-07-05T20:34:06.573239Z?project=smartfinance-bills-beta&query=%0A

```
 2021-07-04 18:22:01.361 BRT
"[INFO] Loaded doc: Planejamento Financeiro v2 on first sheet: Projeção 2021 "
Default
2021-07-04 18:22:01.362 BRT
"[DEBUG] getting month reference "
Default
2021-07-04 18:22:01.407 BRT
"[INFO] current_month: Julho/2021 "
Default
2021-07-04 18:22:03.586 BRT
"[DEBUG] find category cells and set values "
Default
2021-07-04 18:22:04.806 BRT
"[DEBUG] cell row: 22 / value: Condomínio "
Default
2021-07-04 18:22:04.807 BRT
"[DEBUG] previous cell value: null "
Default
2021-07-04 18:22:04.825 BRT
"[DEBUG] cell row: 23 / value: Telefonia/Internet/TV "
Default
2021-07-04 18:22:04.825 BRT
"[DEBUG] previous cell value: null "
Default
2021-07-04 18:22:04.837 BRT
"[DEBUG] cell row: 25 / value: Gas "
Default
2021-07-04 18:22:04.838 BRT
"[DEBUG] previous cell value: null "
Default
2021-07-04 18:22:04.841 BRT
"[DEBUG] cell row: 36 / value: Cursos "
Default
2021-07-04 18:22:04.841 BRT
"[DEBUG] previous cell value: null "
Default
2021-07-04 18:22:04.853 BRT
"[INFO] 5 files processed "
Default
2021-07-04 18:22:04.867 BRT
"(node:7) UnhandledPromiseRejectionWarning: Error: Value has been changed "
Default
2021-07-04 18:22:04.867 BRT
" at GoogleSpreadsheetCell.get value [as value] (/app/node_modules/google-spreadsheet/lib/GoogleSpreadsheetCell.js:37:52) "
" at /app/spreadsheet.js:104:37 "
Default
2021-07-04 18:22:04.867 BRT
" at arrayEach (/app/node_modules/lodash/lodash.js:530:11) "
Default
2021-07-04 18:22:04.867 BRT
" at Function.forEach (/app/node_modules/lodash/lodash.js:9410:14) "
Default
2021-07-04 18:22:04.867 BRT
" at /app/spreadsheet.js:102:12 "
Default
2021-07-04 18:22:04.867 BRT
" at /app/node_modules/lodash/lodash.js:3585:27 "
Default
2021-07-04 18:22:04.868 BRT
" at /app/node_modules/lodash/lodash.js:4967:15 "
Default
2021-07-04 18:22:04.868 BRT
" at baseForOwn (/app/node_modules/lodash/lodash.js:3032:24) "
Default
2021-07-04 18:22:04.868 BRT
" at /app/node_modules/lodash/lodash.js:4936:18 "
Default
2021-07-04 18:22:04.868 BRT
" at baseMap (/app/node_modules/lodash/lodash.js:3584:7) "
```

**Comment by manasouza** [comment]
Fixed
